{{- range .Values.nodes.masters }}
apiVersion: v1
kind: Secret
metadata:
  name: bmc-{{ .name }}-{{ $.Values.global.name }}
  namespace: {{ $.Values.global.namespace }}
data:
  username: {{ .bmc_username | quote | b64enc }}
  password: {{ .bmc_password | quote | b64enc }}
type: Opaque
---
{{- end }}