{{- range .Values.nodes.masters }}
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ .name }}-{{ $.Values.global.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    # InfraEnv to use
    infraenvs.agent-install.openshift.io: "infraenv-{{ $.Values.global.name }}"
  annotations:
    bmac.agent-install.openshift.io/role: {{ .role | default "worker" }}
    bmac.agent-install.openshift.io/hostname: "{{ .name }}"
    inspect.metal3.io: disabled
    # bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: {{ .int1_mac }}
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+{{ .bmc_address }}
    credentialsName: bmc-{{ .name }}-{{ $.Values.global.name }}
    disableCertificateVerification: True
---
{{- end }}