---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telco-ztp-deploy
  namespace: telco-gitops
spec:
  generators:
  - git:
      repoURL: {{ .Values.base_git_url }}
      revision: HEAD 
      directories:
        - path: clusters/*
  template:
    metadata:
      name: '01-ztp-deploy-{{ "{{" }}path.basename{{ "}}" }}'
      namespace: telco-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: {{ .Values.base_git_url }}
        targetRevision: HEAD
        path: '{{ "{{" }}path{{ "}}" }}/ztp'
