---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "30"

bases:
  - ../../../base/configs/telco-gitops

resources:
  - 00-hook-presync-csv.yaml
  - 01-gitops-mgmt-telco-operators.yaml
  - 02-gitops-mgmt-telco-configs.yaml

