---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-master1
  namespace: assisted-installer
  labels:
    nmstate-sno-label: ocptest-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: enp2s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: false
  interfaces:
    - name: "enp1s0"
      macAddress: 52:54:00:e9:0e:fd
    - name: "enp2s0"
      macAddress: 52:54:01:e9:0e:fd
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-master2
  namespace: assisted-installer
  labels:
    nmstate-sno-label: ocptest-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: enp2s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: false
  interfaces:
    - name: "enp1s0"
      macAddress: 52:54:00:96:aa:61
    - name: "enp2s0"
      macAddress: 52:54:01:96:aa:61
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-master3
  namespace: assisted-installer
  labels:
    nmstate-sno-label: ocptest-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: enp2s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: false
  interfaces:
    - name: "enp1s0"
      macAddress: 52:54:00:65:65:56
    - name: "enp2s0"
      macAddress: 52:54:01:65:65:56
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker1
  namespace: assisted-installer
  labels:
    nmstate-sno-label: ocptest-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: enp2s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: false
  interfaces:
    - name: "enp1s0"
      macAddress: 52:54:00:46:8a:bf
    - name: "enp2s0"
      macAddress: 52:54:01:46:8a:bf
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker2
  namespace: assisted-installer
  labels:
    nmstate-sno-label: ocptest-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
      - name: enp2s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: false
  interfaces:
    - name: "enp1s0"
      macAddress: 52:54:00:33:3e:ea
    - name: "enp2s0"
      macAddress: 52:54:01:33:3e:ea
