---
# https://github.com/openshift/assisted-service/blob/master/docs/operator.md#specifying-environmental-variables-via-configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: assisted-installer
data:
  LOG_LEVEL: "debug"
  SUPPORT_L2: "false"
#  DISABLED_HOST_VALIDATIONS: "belongs-to-machine-cidr,belongs-to-majority-group"
  ISO_IMAGE_TYPE: "full-iso"
  PUBLIC_CONTAINER_REGISTRIES: "lab-registry.ocpsmc.lab.diktio.net"
  CONTROLLER_IMAGE: "quay.io/ocpmetal/assisted-installer-controller@sha256:bade2130989677cb734efa2ba01470394b46d88f37849696ee58907a0627b335"
  