---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "4.8"
  installPlanApproval: Automatic
  name: local-storage-operator
  # Modify source name of the catalogsource for isolated network deployments
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace