---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/core-5g: telco-gitops

# NOTE: This node definition

bases:
  #####################################################
  # Operators for core-5G Clusters
  #####################################################
  # Common Telco Optimizations
  - ../../base/configs/telco-optimized
  # Local Storage Operator
  - ../../base/operators/local-storage-operator
  # OpenShift Container storage
  - ../../base/operators/openshift-container-storage
  # OpenShift Logging
  # - ../../base/operators/openshift-logging
  # OpenShiftVirt
  # - ../../base/operators/openshift-virtualization?ref=main
  # Enable SCTP
  - ../../base/configs/sctp
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO
  - ../../base/operators/openshift-performance-addon-operator
  # Configure chrony
  # - ../../base/configs/chrony
  # Identity Provider (htpasswd)
  # - ../../base/configs/idp-htpasswd
  # LSO auto-discovery label
  # - ../../base/configs/lso

