---
# This ZTP has dependency on a management cluster
######
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/ztp: combined-ran

resources:
  - 01-agent-ocptest.yaml
  - 01-cluster-ocptest.yaml
  - 01-infraenv-ocptest.yaml
  - 01-nmstate-ocptest.yaml
#  - 01-nmstate-ocptest-dhcp.yaml
#  - 02-bmh-ocptest.yaml
  - 02-bmh-ocptest-3m.yaml
  - 99-hook-postsync-csv-patch-metal3.yaml