---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: gitops-ztp-{{ .Values.name }}-operator
 namespace: telco-gitops
spec:
  generators:
    - git:
        directories:
          - path: clusters/{{ .Values.name }}.{{ .Values.domain }}/operator-*
        repoURL: '{{ .Values.base_git_url }}'
        revision: HEAD
  template:
    metadata:
      name: '00-{{ .Values.name }}-{{ "{{" }}path.basename{{ "}}" }}'
      namespace: telcot-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://api.{{ .Values.name }}.{{ .Values.domain }}:6443'
      project: default
      source:
        repoURL: '{{ .Values.base_git_url }}'
        targetRevision: HEAD
        path: '{{ "{{" }}path{{ "}}" }}'
