apiVersion: v1
kind: Secret
metadata:
  name: bmc-{{ .Values.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
data:
  username: {{ .Values.bmc_username | quote | b64enc }}
  password: {{ .Values.bmc_password | quote | b64enc }}
type: Opaque
